algorithm: supervised
save_dir: ./saved_models/data1/train_10%
save_name: supervised_data1_10%_0
resume: False
load_path: None
overwrite: True
use_tensorboard: True
use_wandb: False
epoch: 100
num_train_iter: 200000
num_eval_iter: 100
num_log_iter: 100
num_labels: 250 #有标记标签数量
train_lb: 0.1 #有标记标签百分比
batch_size: 64
eval_batch_size: 1024
ema_m: 0.999
crop_ratio: 1
img_size: 6
optim: SGD
lr: 0.03
momentum: 0.9
weight_decay: 0.0005
layer_decay: 1.0
amp: False
clip: 0.0
use_cat: True
net: wrn_28_2
net_from_name: False
data_dir: ./data1
dataset: jmdata
train_sampler: RandomSampler
num_classes: 4
num_workers: 1
seed: 0
world_size: 1
rank: 0
multiprocessing_distributed: True
dist_url: tcp://127.0.0.1:10024
dist_backend: nccl
gpu: None
